export const Prompts = [
  'What are 3 amazing things that happened today?',
  'Think about one person who makes you feel loved. How do they show you that they care?',
  'Who do you trust most? Why?',
  'What are your strengths in relationships (kindness, empathy, etc.)?',
  'How do you draw strength from loved ones?',
  'What do you value most in relationships (trust, respect, sense of humor, etc.)?',
  'What three important things have you learned from previous relationships?',
  'What five traits do you value most in potential partners?',
  'How do you show compassion to others? How can you extend that same compassion to yourself?',
  'What are three things working well in your current relationship? What are things that could be better?',
  'What boundaries could you set in your relationships to safeguard your own ',
  'well-being?',
  'What do you most want your children (or future children) to learn from you?',
  'How can you better support and appreciate your loved ones?',
  'What does love mean to you? How do you recognize it in a relationship?',
  'List three things you’d like to tell a friend, family member, or partner.',
  'How do you use your personal strengths and abilities at work?',
  'How do your co-workers and supervisors recognize your strengths?',
  'How does work fulfill you? Does it leave you wanting more?',
  'What part of your workday do you most enjoy?',
  'What about your work feels real, necessary, or important to you?',
  'Do you see yourself in the same job in 10 years?',
  'What are your career ambitions?',
  'What three things can help you begin working to accomplish those goals?',
  'What can you do to improve your work performance?',
  'What does your work teach you? Does it offer continued opportunities for learning and growth?',
  'Does your work drain or overwhelm you? Why? Is this something you can change?',
  'What values do you consider most important in life (honesty, justice, altruism, loyalty, etc.)? How do your actions align with those values?',
  'What three changes can you make to live according to your personal values?',
  'Describe yourself using the first 10 words that come to mind. Then, list 10 words that you’d like to use to describe yourself. List a few ways to transform those descriptions into reality.',
  'What do you appreciate most about your personality? What aspects do you find harder to accept?',
  'Explore an opinion or two that you held in the past but have since questioned or changed. What led you to change that opinion?',
  'List three personal beliefs that you’re willing to reconsider or further explore.',
  'Finish this sentence: “My life would be incomplete without …”',
  'Describe one or two significant life events that helped shape you into who you are today.',
  'When do you trust yourself most? When do you find it harder to have faith in your instincts?',
  'What three things would you most like others (loved ones, potential friends and partners, professional acquaintances, etc.) to know about you?',
  'What difficult thoughts or emotions come up most frequently for you?',
  'Which emotions do you find hardest to accept (guilt, anger, disappointment, etc.)? How do you handle these emotions?',
  'Describe a choice you regret. What did you learn from it?',
  'What parts of daily life cause stress, frustration, or sadness? What can you do to change those experiences?',
  'What are three things that can instantly disrupt a good mood and bring you down? What strategies do you use to counter these effects?',
  'What are three self-defeating thoughts that show up in your self-talk? How can you reframe them to encourage yourself instead?',
  'What go-to coping strategies help you get through moments of emotional or physical pain?',
  'Who do you trust with your most painful and upsetting feelings? How can you connect with them when feeling low?',
  'What do you fear most? Have your fears changed throughout life?',
  'Describe your favorite thing to do when feeling low.',
  'What three ordinary things bring you the most joy?',
  'List three strategies that help you stay present in your daily routines. Then, list three strategies to help boost mindfulness in your life.',
  'How do you prioritize self-care?',
  'Describe two or three things you do to relax.',
  'What aspects of your life are you most grateful for?',
  'How do you show yourself kindness and compassion each day?',
  'Write a short love letter to some object or place that makes you happy.',
  'What place makes you feel most peaceful? Describe that place using all five senses.',
  'List 10 things that inspire or motivate you.',
  'What are your favorite hobbies? Why?',
  'What parts of life surprised you most? What turned out the way you expected it would?',
  'What three things would you share with your teenage self? What three questions would you want to ask an older version of yourself?',
  'List three important goals. How do they match up to your goals from 5 years ago?',
  'Do your goals truly reflect your desires? Or do they reflect what someone else (a parent, partner, friend, etc.) wants for you?',
  'What helps you stay focused and motivated when you feel discouraged?',
  'What do you look forward to most in the future?',
  'Identify one area where you’d like to improve. Then, list three specific actions you can take to create that change.',
  'How do you make time for yourself each day?',
  'What do you most want to accomplish in life?',
  'List three obstacles lying in the way of your contentment or happiness. Then, list two potential solutions to begin overcoming each obstacle.',
];
